export {
  DEFAULT_PLATFORM_VALUE,
  PROJECT_AREAS,
  PROJECT_THEMES_BY_AREA,
  buildClienteProjectTypeLabel,
  PLATFORMS,
  URGENCY_LEVELS,
  TARGET_AUDIENCES,
  FEATURE_SUGGESTION_GROUPS,
  PROCESS_FREQUENCIES,
  PROCESS_FREQUENCY_MULTIPLIERS,
  HAS_EXISTING_SYSTEM_OPTIONS,
  BENEFIT_OPTIONS,
} from "@/shared/constants/project-taxonomy";
